steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/argos-proof-of-concept/argos-poc-repo/argos-poc:latest', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/argos-proof-of-concept/argos-poc-repo/argos-poc:latest']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'argos-pos-service' # You can change this service name
  - '--image'
  - 'us-central1-docker.pkg.dev/argos-proof-of-concept/argos-poc-repo/argos-poc:latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8000'
  # The following environment variables are needed by the application.
  # They are injected from Secret Manager.
  - '--set-secrets'
  - 'GOOGLE_API_KEY=ARGOS_GOOGLE_API_KEY:latest'
  - '--set-secrets'
  - 'REDIS_HOST=ARGOS_REDIS_HOST:latest'
  - '--set-secrets'
  - 'REDIS_PORT=ARGOS_REDIS_PORT:latest'
  - '--set-secrets'
  - 'TAVILY_API_KEY=ARGOS_TAVILY_API_KEY:latest'

images:
- 'us-central1-docker.pkg.dev/argos-proof-of-concept/argos-poc-repo/argos-poc:latest'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/ARGOS_GOOGLE_API_KEY/versions/latest
    env: 'GOOGLE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/ARGOS_REDIS_HOST/versions/latest
    env: 'REDIS_HOST'
  - versionName: projects/$PROJECT_ID/secrets/ARGOS_REDIS_PORT/versions/latest
    env: 'REDIS_PORT'
  - versionName: projects/$PROJECT_ID/secrets/ARGOS_TAVILY_API_KEY/versions/latest
    env: 'TAVILY_API_KEY'